# Generated by Django 5.2.2 on 2026-07-17 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_category_newsletter_order_user_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cateringenquiry",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Approximate budget in INR",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="cateringenquiry",
            name="catering_package",
            field=models.CharField(
                choices=[
                    ("basic", "Basic — Ice Cream Tub Service"),
                    ("standard", "Standard — Ice Cream + Toppings Bar"),
                    ("premium", "Premium — Full Dessert Catering"),
                    ("custom", "Custom — Tailored Package"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cateringenquiry",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="We'll send a confirmation to this email",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="cateringenquiry",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional: upload a reference image or mood board",
                upload_to="catering_references/",
            ),
        ),
        migrations.AddField(
            model_name="cateringenquiry",
            name="special_requirements",
            field=models.TextField(
                blank=True,
                help_text="Dietary restrictions, allergies, preferred flavours, etc.",
            ),
        ),
        migrations.AddField(
            model_name="cateringenquiry",
            name="venue",
            field=models.CharField(
                blank=True, help_text="Where will the event be held?", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="cateringenquiry",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("birthday", "Birthday Party"),
                    ("wedding", "Wedding / Reception"),
                    ("corporate", "Corporate Event"),
                    ("college", "College Fest"),
                    ("family", "Family Gathering"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="cateringenquiry",
            index=models.Index(
                fields=["event_type"], name="home_cateri_event_t_34b20c_idx"
            ),
        ),
    ]
