# Generated by Django 5.2.2 on 2026-07-17 15:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_order_delivery_charge_order_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="flavours",
            field=models.JSONField(
                blank=True, default=list, help_text="Available flavours as JSON array"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, help_text="List of ingredients"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new_arrival",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.JSONField(
                blank=True, default=list, help_text="Available sizes as JSON array"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="toppings",
            field=models.JSONField(
                blank=True, default=list, help_text="Available toppings as JSON array"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="home_produc_is_feat_9da71b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_best_seller"], name="home_produc_is_best_fdb0b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_new_arrival"], name="home_produc_is_new__c29cb5_idx"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="home.product",
            ),
        ),
    ]
