# Generated by Django 5.2.2 on 2026-07-31 09:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_seed_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="CateringPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown on the booking page",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stored on catering enquiries (e.g. basic, standard)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji icon shown on the package card (e.g. 🍦)",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_guest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Base price per guest in INR",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "minimum_guests",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Minimum guest count required for this package",
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="GST percentage applied to the subtotal",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "additional_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed add-on charge (e.g. setup fee) in INR",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "additional_charges_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label for the add-on charge (e.g. 'Setup & Service Fee')",
                        max_length=100,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features shown on the package card",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catering Package",
                "verbose_name_plural": "Catering Packages",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="home_cateri_slug_2d75af_idx"),
                    models.Index(
                        fields=["is_active"], name="home_cateri_is_acti_f82005_idx"
                    ),
                ],
            },
        ),
    ]
