# Generated by Django 5.2.2 on 2026-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_seed_catering_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cateringenquiry",
            name="catering_package",
            field=models.CharField(
                default="basic",
                help_text="Slug of the selected CateringPackage",
                max_length=50,
            ),
        ),
    ]
